version: '3'

services:
  pocket-crud-api:
    build:
      context: .
      args:
        - API_PORT=${API_PORT}
    command: yarn start:prod
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - pocket-crud-psql
    restart: unless-stopped

  pocket-crud-psql:
    image: bitnami/postgresql:15.1.0
    ports:
      - 127.0.0.1:${POSTGRESQL_PORT}:5432
    volumes:
      - pocket-crud-psql-volume:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    restart: unless-stopped

volumes:
  pocket-crud-psql-volume:
